apiVersion: batch/v1
kind: Job
metadata:
  namespace: 
  name: 
spec:
  template:
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}   
      containers:
      - name: eahrend-cypress
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- range $key, $value := .Values.c_env }}
        - name: {{ $key | upper }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.test_envs }}
        - name: {{ $key | upper }}
          value: {{ $value | quote }}
        {{- end }}
      restartPolicy: Never
  backoffLimit: 4